// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home(items map[string]map[string]string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = headerComponent("Services").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<body class=\"min-h-screen bg-gradient-to-b\"><!-- Header with Links --><div class=\"container mx-auto px-4 py-8 flex justify-center\"><div class=\"grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6\"><div class=\"card bg-neutral bg-clip-border shadow-lg rounded-lg hover:shadow-xl text-neutral-content w-72\"><div class=\"card-body items-center text-center\"><h2 class=\"card-title\">Application!</h2><p>Create a new starK8.</p><div class=\"card-actions justify-end\"><button class=\"btn btn-success rounded-lg\" onclick=\"my_modal_1.showModal()\" hx-get=\"/new\" hx-trigger=\"click\" hx-target=\"#my_modal_1\" hx-swap=\"innerHTML\">Create</button> <dialog id=\"my_modal_1\" class=\"modal modal-top py-16 flex justify-center rounded-lg\"></dialog></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for key, value := range items {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 templ.SafeURL = templ.SafeURL(value["externalURL"])
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var2)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"block bg-neutral text-neutral-content shadow-lg rounded-lg overflow-hidden hover:shadow-xl hover:scale-105 transform transition duration-300\"><img src=\"https://via.placeholder.com/400x200\" alt=\"Card Image\" class=\"w-full h-32 object-cover\"><div class=\"p-4\"><h2 class=\"text-xl font-semibold text-center text-white-800\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(key)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/home.templ`, Line: 26, Col: 93}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h2></div></a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

//             <!-- Card 1 -->

//             <!-- Card 2 -->
//             <a href="#" class="block bg-white shadow-lg rounded-lg overflow-hidden hover:shadow-xl hover:scale-105 transform transition duration-300">
//                 <img src="https://via.placeholder.com/400x200" alt="Card Image" class="w-full h-32 object-cover">
//                 <div class="p-4">
//                     <h2 class="text-xl font-semibold text-center">Card Title 2</h2>
//                 </div>
//             </a>
//             <!-- Card 3 -->
//             <a href="#" class="block bg-white shadow-lg rounded-lg overflow-hidden hover:shadow-xl hover:scale-105 transform transition duration-300">
//                 <img src="https://via.placeholder.com/400x200" alt="Card Image" class="w-full h-32 object-cover">
//                 <div class="p-4">
//                     <h2 class="text-xl font-semibold text-center">Card Title 3</h2>
//                 </div>
//             </a>
//             <!-- Card 4 -->
//             <a href="#" class="block bg-white shadow-lg rounded-lg overflow-hidden hover:shadow-xl hover:scale-105 transform transition duration-300">
//                 <img src="https://via.placeholder.com/400x200" alt="Card Image" class="w-full h-32 object-cover">
//                 <div class="p-4">
//                     <h2 class="text-xl font-semibold text-center">Card Title 4</h2>
//                 </div>
//             </a>
//             <!-- Add more cards as needed -->
