// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = headerComponent().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex justify-center\"><div class=\"card w-full max-w-xs br-neutral shadow-xl\"><div class=\"card-body\"><h1 class=\"card-title text-center justify-center w-full\">Log In</h1><form hx-post=\"/users/login\"><!-- Input per Email --><div class=\"form-control\"><label for=\"username\" class=\"label\"><span class=\"label-text\">Username</span></label> <input type=\"username\" id=\"username\" name=\"username\" placeholder=\"username\" class=\"input input-bordered w-full\" required></div><!-- Input per Password --><div class=\"form-control mt-4\"><label for=\"password\" class=\"label\"><span class=\"label-text\">Password</span></label> <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"password\" class=\"input input-bordered w-full\" required></div><!-- Link per Password Dimenticata --><!-- Pulsante per Inviare --><div class=\"form-control mt-8\"><button type=\"submit\" class=\"btn btn-primary w-full\">Log In</button></div></form><div class=\"flex items-center justify-between mt-4\"><span class=\"w-1/5 border-b dark:border-gray-600 md:w-1/4\"></span> <a class=\"text-xs text-gray-600 uppercase dark:text-gray-500 hover:underline\" href=\"/users/sign_up\">or sign up</a> <span class=\"w-1/5 border-b dark:border-gray-400 md:w-1/4\"></span></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
